language: ruby

sudo: required

os:
  - osx
  - linux

osx_image: xcode7.3

install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` = "Linux" ]; then bash setup_travis_linux.sh; fi
  - if [ `uname` = "Linux" ]; then export PATH="$HOME/.linuxbrew/bin:$PATH"; export HOMEBREW_BUILD_FROM_SOURCE=1; fi
  - brew update
  - if [ `uname` = "Linux" ]; then brew install pkg-config; fi
  - brew update
  - brew tap homebrew/science
  # Install homebrew/cutest as tap.
  - mkdir -p $(brew --repo)/Library/Taps/optimizers
  - ln -s $PWD $(brew --repo)/Library/Taps/optimizers/homebrew-cutest
  - brew tap --repair

env:
  - PACKAGE=archdefs
  - PACKAGE=sifdecode
  - PACKAGE=cutest
  - PACKAGE=mastsif
  - PACKAGE=maros_meszaros

script:
  #- brew audit $PACKAGE --strict  # Fails for now b/c head only.
  - brew install -v $PACKAGE
  - brew test -v $PACKAGE
